### ISSUE TITLE
QuPath_to_xml: Export Name and class

### ISSUE THREAD

**Issue by mariokreutzfeldt** [pjl54/Util#1] opened 2020-03-03 13:39 UTC
First of all, thank you for this nice script!

I have 2 questions:
1) Would it be possible to export the class and name of the annotation, too? After re-importing the annotations with the script "xml_to_QuPath.groovy", colors are correct, but name and class are filled with unique 8-digit numbers.

2) When I import the XML with another program e.g. [ASAP ](https://github.com/computationalpathologygroup/ASAP/releases/tag/1.9), the annotations get shifted in +Y direction.

Thank you and best regards,
Mario

**Comment by pjl54** [comment] 2020-03-04 18:59
Glad you're finding this code useful.

1. I hope to find a way to add that. One of the issues is that if your installation of QuPath has a class called "Tumor" that is red, but you are loading an xml file that has a class called "Tumor" that is green, it is not clear what color the imported annotation should be. You should be faithful to the xml, but you also can't have two classes with the same name and different colors. To avoid that, I made the class name be the RGB integer of the line color. 

2. Could you provide some more details about this error? What image format did you use and how much were the annotations shifted? I tested an .svs image with qupath-0.20-m9 and ASAP 1.9.0 and the annotations created in Qupath, saved to xml, then loaded in ASAP seemed correct.

**Comment by mariokreutzfeldt** [comment] 2020-03-05 08:29
Hi,
thank you for your reply.
 
1) Makes sense in case of classes with identical names. But in my case I created a new unique class with unique color and still the RGB integer was written into the name and class field after reimporting the XML. That said, I would priorize correct class name over "correct" color.

2) The problem seems to arise only with MRXS files. QuPath opens the images "cropped" (whitespace removed), while ASAP opens them full. The shift is the difference between the croppend and full origin coordinates.

Cheers,
Mario

**Comment by pjl54** [comment] 2020-03-06 15:19
1. When determining the properties for a newly added annotation, Qupath ignores the color input if the class already exists. So if a class called "Tumor" already exists in your installation, any new annotations in the "Tumor" class will be the same color as the existing class. There is no way to override this as far as I can tell. 

I just pushed an update to qupath_to_xml that saves the annotation class name and an update to xml_to_qupath that will import annotations to the named class, so long as that class exists in your installation and the class color in your installation matches the color of that annotation in the xml. 

I didn't allow importing the annotation to a class of the same name but different color so that if you are also working with these files in Imagescope or ASAP, the colors wouldn't be changed if you edited the annotation in a Qupath installation with a different class color scheme than the one used by the creator of the xml. However, when you save this xml, it will lose the class label and you'll have to relabel it.

Ultimately, the annotation color is trustworthy and is preserved, the annotation class name is not trustworthy and can be changed by loading and saving the same file. But if you are using a single Qupath installation or are only using the default classes or creating the appropriate classes before importing an xml, the class labels should be preserved. If you want to always match the class color of the local installation based on the class name in the xml, you can remove the check for same line color in xml_to_qupath:

`if(pathclassLocal.getColor() - (255<<24) == linecolor) {`

2. It is possible that this would be fixed by replacing the current coordinate-getting loop with the following, though I have not thoroughly tested this. The problem is that mrxs files use two coordinate systems, one system originating at the slide boundary, the other originating at the tissue bounding box boundary. While Qupath stores coordinates based on one system, ASAP uses the other system. 

```
def x = getCurrentServer().boundsX
def y = getCurrentServer().boundsY

// the last coordinate is (0.0,0.0)
if(coordinates[0] > 0 && coordinates[1] > 0) {
Vertex.setAttribute('X',String.valueOf(coordinates[0]+x))
Vertex.setAttribute('Y',String.valueOf(coordinates[1]+y))
Vertices.appendChild(Vertex)
}
```

Please let me know if these fixes solved your problems. I haven't had a chance to test them in all scenarios.

**Comment by mariokreutzfeldt** [comment] 2020-03-09 08:22
Thank you for pushing these fixes. 
I have tested the XML export / import and it works as expected. I will keep it's limitations in mind!
As for the second fix, I will try to test it later this week. 

Best regards,
Mario

p.s.: since the second point was not really the topic of this issue, feel free to close it!

**Comment by pjl54** [comment] 2020-03-14 17:46
Great, glad it worked! If you run into anything else, please feel free to reopen or start a new a issue.

**Closed by pjl54** 2020-03-14 17:46 UTC
